#pragma once
// AUTO-GENERATED by scripts/box0_gen_config.py from box0_config.ini.
// Edit box0_config.ini and run flash_box0.bat - do not edit this file.
#define BOX0_WIFI_SSID "iKuai-1024"
#define BOX0_WIFI_PASSWORD "wanqing1002"
