#pragma once
// AUTO-GENERATED by scripts/box0_gen_config.py from box0_config.ini.
// Edit box0_config.ini and run flash_box0.bat - do not edit this file.
#define BOX0_WIFI_SSID "iKuai-1024-2.4G"
#define BOX0_WIFI_PASSWORD "wanqing1002"
#define BOX0_WIFI2_SSID "Ziroom901_1"
#define BOX0_WIFI2_PASSWORD "4001001111"
