#!/usr/bin/env python3
# Generate box0_local_config.h from box0_config.ini (run by flash_box0.bat).
import configparser
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INI = os.path.join(ROOT, 'box0_config.ini')
HEADER = os.path.join(ROOT, 'main', 'boards', 'alientek', 'atk-dnesp32s3-box0', 'box0_local_config.h')
QT = chr(34)


def c_escape(s):
    bs = chr(92)
    return s.replace(bs, bs + bs).replace(QT, bs + QT)


def main():
    if not os.path.exists(INI):
        print('[box0_gen_config] ERROR: %s not found' % INI, file=sys.stderr)
        return 1
    cp = configparser.ConfigParser()
    cp.read(INI, encoding='utf-8')
    networks = []
    for section in cp.sections():
        if section == 'wifi' or (section.startswith('wifi') and section[4:].isdigit()):
            ssid = cp.get(section, 'ssid', fallback='').strip()
            password = cp.get(section, 'password', fallback='').strip()
            if not ssid:
                print('[box0_gen_config] ERROR: wifi.ssid is empty in section [%s]' % section, file=sys.stderr)
                return 1
            networks.append((ssid, password))
    if not networks:
        print('[box0_gen_config] ERROR: no [wifi] section in box0_config.ini', file=sys.stderr)
        return 1
    lines = [
        '#pragma once',
        '// AUTO-GENERATED by scripts/box0_gen_config.py from box0_config.ini.',
        '// Edit box0_config.ini and run flash_box0.bat - do not edit this file.',
    ]
    for i, (ssid, password) in enumerate(networks):
        suffix = '' if i == 0 else str(i + 1)
        lines.append(chr(35) + 'define BOX0_WIFI' + suffix + '_SSID ' + QT + c_escape(ssid) + QT)
        lines.append(chr(35) + 'define BOX0_WIFI' + suffix + '_PASSWORD ' + QT + c_escape(password) + QT)
    content = chr(10).join(lines) + chr(10)
    if os.path.exists(HEADER):
        with io.open(HEADER, 'r', encoding='utf-8') as f:
            if f.read() == content:
                print('[box0_gen_config] unchanged (ssid=%s)' % networks[0][0])
                return 0
    with io.open(HEADER, 'w', encoding='utf-8', newline=chr(10)) as f:
        f.write(content)
    print('[box0_gen_config] wrote %s (%d networks, first ssid=%s)' % (HEADER, len(networks), networks[0][0]))
    return 0


if __name__ == '__main__':
    sys.exit(main())
