#!/usr/bin/env python3
# Generate box0_local_config.h from box0_config.ini (run by flash_box0.bat).
import configparser
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INI = os.path.join(ROOT, 'box0_config.ini')
HEADER = os.path.join(ROOT, 'main', 'boards', 'alientek', 'atk-dnesp32s3-box0', 'box0_local_config.h')
QT = chr(34)


def c_escape(s):
    bs = chr(92)
    return s.replace(bs, bs + bs).replace(QT, bs + QT)


def main():
    if not os.path.exists(INI):
        print('[box0_gen_config] ERROR: %s not found' % INI, file=sys.stderr)
        return 1
    cp = configparser.ConfigParser()
    cp.read(INI, encoding='utf-8')
    ssid = cp.get('wifi', 'ssid', fallback='').strip()
    password = cp.get('wifi', 'password', fallback='').strip()
    if not ssid:
        print('[box0_gen_config] ERROR: wifi.ssid is empty in box0_config.ini', file=sys.stderr)
        return 1
    content = chr(10).join([
        '#pragma once',
        '// AUTO-GENERATED by scripts/box0_gen_config.py from box0_config.ini.',
        '// Edit box0_config.ini and run flash_box0.bat - do not edit this file.',
        chr(35) + 'define BOX0_WIFI_SSID ' + QT + c_escape(ssid) + QT,
        chr(35) + 'define BOX0_WIFI_PASSWORD ' + QT + c_escape(password) + QT,
        '',
    ])
    if os.path.exists(HEADER):
        with io.open(HEADER, 'r', encoding='utf-8') as f:
            if f.read() == content:
                print('[box0_gen_config] unchanged (ssid=%s)' % ssid)
                return 0
    with io.open(HEADER, 'w', encoding='utf-8', newline=chr(10)) as f:
        f.write(content)
    print('[box0_gen_config] wrote %s (ssid=%s)' % (HEADER, ssid))
    return 0


if __name__ == '__main__':
    sys.exit(main())
